CREATE TABLE "doctores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150),
  "especialidad" varchar(150),
  "fecha_registro" timestamp DEFAULT 'now()'
);

CREATE TABLE "pacientes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150),
  "correo" varchar(150),
  "telefono" varchar(25),
  "fecha_registro" timestamp DEFAULT 'now()'
);

CREATE TABLE "citas" (
  "doctor_id" integer,
  "paciente_id" integer,
  "fecha_cita" timestamp,
  "estado" char(1),
  "fecha_registro" timestamp DEFAULT 'now()'
);

ALTER TABLE "citas" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "citas" ADD FOREIGN KEY ("paciente_id") REFERENCES "pacientes" ("id") DEFERRABLE INITIALLY IMMEDIATE;
