CREATE TABLE "especialidades" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150)
);

INSERT INTO especialidades (nombre) VALUES
('Cargiología'),
('Endocrinología'),
('Medicina General');

INSERT INTO citas (doctor_id, paciente_id, fecha_cita)
VALUES (1,2,'2025-03-17 20:50:00');